services:
  - name: flask-app
    type: web
    plan: free
    region: oregon
    env: python
    build_command: pip install -r requirements.txt
    start_command: python main1.py
    autoDeploy: true
    debug: true
    envVars:
      - key: PORT
        value: 5000
